# Generated by Django 6.0.1 on 2026-03-04 16:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_type', models.CharField(choices=[('SEGMENT', 'Customer Segment Analysis'), ('UPSELL', 'Upsell Opportunity'), ('CHURN', 'Churn Alert'), ('GROWTH', 'Growth Opportunity')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=10)),
                ('metric_value', models.CharField(blank=True, help_text="e.g., '4.2%', '12 accounts'", max_length=100)),
                ('recommendation', models.TextField(blank=True)),
                ('action_plan', models.JSONField(blank=True, default=dict, help_text='Structured action items')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'customer_analytics_insight',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_customers', models.IntegerField(default=0)),
                ('total_customers_change', models.DecimalField(decimal_places=2, default=0, help_text='Percentage change', max_digits=5)),
                ('retention_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('retention_rate_change', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('avg_lifetime_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('avg_lifetime_value_change', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('churn_risk_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('churn_risk_change', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('vip_tier_count', models.IntegerField(default=0)),
                ('regular_tier_count', models.IntegerField(default=0)),
                ('new_signup_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'customer_analytics_kpi',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('loyalty_tier', models.CharField(choices=[('VIP', 'VIP Tier'), ('REGULAR', 'Regulars'), ('NEW', 'New Signups')], default='NEW', max_length=10)),
                ('is_vip', models.BooleanField(default=False)),
                ('lifetime_value', models.DecimalField(decimal_places=2, default=0, help_text='Total revenue generated by this customer', max_digits=12)),
                ('total_purchases', models.IntegerField(default=0)),
                ('average_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('last_purchase_date', models.DateField(blank=True, null=True)),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('churn_risk_score', models.IntegerField(default=0, help_text='0-100 score indicating likelihood of churn', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_at_risk', models.BooleanField(default=False, help_text='Customer flagged as at-risk')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'customer_analytics_customer',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='customer_an_email_4095c9_idx'), models.Index(fields=['loyalty_tier'], name='customer_an_loyalty_a26fa3_idx'), models.Index(fields=['is_at_risk'], name='customer_an_is_at_r_d37627_idx')],
            },
        ),
        migrations.CreateModel(
            name='CustomerBehavior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(help_text='Format: YYYY-MM', max_length=7)),
                ('purchase_frequency', models.IntegerField(default=0, help_text='Number of purchases in the month')),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('average_days_between_purchases', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behaviors', to='customer_analytics.customer')),
            ],
            options={
                'db_table': 'customer_analytics_behavior',
                'ordering': ['-month'],
                'indexes': [models.Index(fields=['month'], name='customer_an_month_8ae031_idx')],
                'unique_together': {('customer', 'month')},
            },
        ),
        migrations.CreateModel(
            name='PurchaseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('items_count', models.IntegerField(default=1)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_records', to='customer_analytics.customer')),
            ],
            options={
                'db_table': 'customer_analytics_purchase_record',
                'ordering': ['-purchase_date'],
                'indexes': [models.Index(fields=['purchase_date'], name='customer_an_purchas_f4130f_idx'), models.Index(fields=['customer', 'purchase_date'], name='customer_an_custome_b3f048_idx')],
            },
        ),
        migrations.CreateModel(
            name='RecentActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('SALE', 'New sale record created'), ('LEAD_STATUS', 'Lead status changed'), ('EXPORT', 'Data export requested'), ('REGISTRATION', 'New customer registration'), ('TIER_CHANGE', 'Loyalty tier changed')], max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='customer_analytics.customer')),
            ],
            options={
                'verbose_name_plural': 'Recent Activities',
                'db_table': 'customer_analytics_recent_activity',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='customer_an_timesta_cef877_idx')],
            },
        ),
    ]
