from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from decimal import Decimal


class Customer(models.Model):
    """
    Core customer information
    """
    TIER_CHOICES = [
        ('VIP', 'VIP Tier'),
        ('REGULAR', 'Regulars'),
        ('NEW', 'New Signups'),
    ]
    
    full_name = models.CharField(max_length=255)
    email = models.EmailField(unique=True)
    phone = models.CharField(max_length=20, blank=True, null=True)
    loyalty_tier = models.CharField(max_length=10, choices=TIER_CHOICES, default='NEW')
    is_vip = models.BooleanField(default=False)
    
    # Financial metrics
    lifetime_value = models.DecimalField(
        max_digits=12, 
        decimal_places=2, 
        default=0,
        help_text="Total revenue generated by this customer"
    )
    total_purchases = models.IntegerField(default=0)
    average_order_value = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    
    # Engagement metrics
    last_purchase_date = models.DateField(null=True, blank=True)
    registration_date = models.DateField(auto_now_add=True)
    churn_risk_score = models.IntegerField(
        default=0,
        validators=[MinValueValidator(0), MaxValueValidator(100)],
        help_text="0-100 score indicating likelihood of churn"
    )
    is_at_risk = models.BooleanField(default=False, help_text="Customer flagged as at-risk")
    
    # Status
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        db_table = 'customer_analytics_customer'
        ordering = ['-created_at']
        indexes = [
            models.Index(fields=['email']),
            models.Index(fields=['loyalty_tier']),
            models.Index(fields=['is_at_risk']),
        ]
    
    def __str__(self):
        return f"{self.full_name} ({self.email})"
    
    def update_metrics(self):
        """Update calculated metrics based on purchase history"""
        from django.db.models import Sum, Avg, Count
        purchases = self.purchase_records.all()
        
        if purchases.exists():
            self.total_purchases = purchases.count()
            self.lifetime_value = purchases.aggregate(Sum('amount'))['amount__sum'] or 0
            self.average_order_value = purchases.aggregate(Avg('amount'))['amount__avg'] or 0
            self.last_purchase_date = purchases.latest('purchase_date').purchase_date
            
            # Update tier based on metrics
            if self.lifetime_value >= 100000:  # PKR 100,000+
                self.loyalty_tier = 'VIP'
                self.is_vip = True
            elif self.total_purchases >= 5:
                self.loyalty_tier = 'REGULAR'
                self.is_vip = False
            else:
                self.loyalty_tier = 'NEW'
                self.is_vip = False
                
        self.save()


class CustomerBehavior(models.Model):
    """
    Tracks customer purchase behavior and frequency
    """
    customer = models.ForeignKey(
        Customer, 
        on_delete=models.CASCADE, 
        related_name='behaviors'
    )
    month = models.CharField(max_length=7, help_text="Format: YYYY-MM")
    purchase_frequency = models.IntegerField(default=0, help_text="Number of purchases in the month")
    total_spent = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    average_days_between_purchases = models.IntegerField(default=0)
    
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        db_table = 'customer_analytics_behavior'
        unique_together = ['customer', 'month']
        ordering = ['-month']
        indexes = [
            models.Index(fields=['month']),
        ]
    
    def __str__(self):
        return f"{self.customer.full_name} - {self.month}"


class PurchaseRecord(models.Model):
    """
    Individual purchase transactions for tracking customer history
    """
    customer = models.ForeignKey(
        Customer, 
        on_delete=models.CASCADE, 
        related_name='purchase_records'
    )
    purchase_date = models.DateField()
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    items_count = models.IntegerField(default=1)
    payment_method = models.CharField(max_length=50, blank=True)
    
    created_at = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        db_table = 'customer_analytics_purchase_record'
        ordering = ['-purchase_date']
        indexes = [
            models.Index(fields=['purchase_date']),
            models.Index(fields=['customer', 'purchase_date']),
        ]
    
    def __str__(self):
        return f"{self.customer.full_name} - PKR {self.amount} on {self.purchase_date}"


class RecentActivity(models.Model):
    """
    Tracks recent customer activities for the dashboard
    """
    ACTIVITY_TYPES = [
        ('SALE', 'New sale record created'),
        ('LEAD_STATUS', 'Lead status changed'),
        ('EXPORT', 'Data export requested'),
        ('REGISTRATION', 'New customer registration'),
        ('TIER_CHANGE', 'Loyalty tier changed'),
    ]
    
    customer = models.ForeignKey(
        Customer, 
        on_delete=models.CASCADE, 
        related_name='activities',
        null=True,
        blank=True
    )
    activity_type = models.CharField(max_length=20, choices=ACTIVITY_TYPES)
    description = models.CharField(max_length=255)
    metadata = models.JSONField(default=dict, blank=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        db_table = 'customer_analytics_recent_activity'
        ordering = ['-timestamp']
        verbose_name_plural = 'Recent Activities'
        indexes = [
            models.Index(fields=['-timestamp']),
        ]
    
    def __str__(self):
        return f"{self.activity_type} - {self.description}"


class CustomerInsight(models.Model):
    """
    AI-generated insights and recommendations for CRM
    """
    INSIGHT_TYPES = [
        ('SEGMENT', 'Customer Segment Analysis'),
        ('UPSELL', 'Upsell Opportunity'),
        ('CHURN', 'Churn Alert'),
        ('GROWTH', 'Growth Opportunity'),
    ]
    
    PRIORITY_LEVELS = [
        ('HIGH', 'High'),
        ('MEDIUM', 'Medium'),
        ('CRITICAL', 'Critical'),
    ]
    
    insight_type = models.CharField(max_length=20, choices=INSIGHT_TYPES)
    title = models.CharField(max_length=255)
    description = models.TextField()
    priority = models.CharField(max_length=10, choices=PRIORITY_LEVELS, default='MEDIUM')
    metric_value = models.CharField(max_length=100, blank=True, help_text="e.g., '4.2%', '12 accounts'")
    
    # Recommendations
    recommendation = models.TextField(blank=True)
    action_plan = models.JSONField(default=dict, blank=True, help_text="Structured action items")
    
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        db_table = 'customer_analytics_insight'
        ordering = ['-created_at']
    
    def __str__(self):
        return f"{self.insight_type} - {self.title}"


class CustomerKPI(models.Model):
    """
    Stores historical KPI data for tracking trends
    """
    date = models.DateField(unique=True)
    
    # Main KPIs
    total_customers = models.IntegerField(default=0)
    total_customers_change = models.DecimalField(
        max_digits=5, 
        decimal_places=2, 
        default=0,
        help_text="Percentage change"
    )
    
    retention_rate = models.DecimalField(
        max_digits=5, 
        decimal_places=2, 
        default=0,
        validators=[MinValueValidator(0), MaxValueValidator(100)]
    )
    retention_rate_change = models.DecimalField(max_digits=5, decimal_places=2, default=0)
    
    avg_lifetime_value = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    avg_lifetime_value_change = models.DecimalField(max_digits=5, decimal_places=2, default=0)
    
    churn_risk_percentage = models.DecimalField(
        max_digits=5, 
        decimal_places=2, 
        default=0,
        validators=[MinValueValidator(0), MaxValueValidator(100)]
    )
    churn_risk_change = models.DecimalField(max_digits=5, decimal_places=2, default=0)
    
    # Tier distribution
    vip_tier_count = models.IntegerField(default=0)
    regular_tier_count = models.IntegerField(default=0)
    new_signup_count = models.IntegerField(default=0)
    
    created_at = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        db_table = 'customer_analytics_kpi'
        ordering = ['-date']
    
    def __str__(self):
        return f"KPIs for {self.date}"
